[workspace]

members = [
    "contract-ffi",
    "engine-core",
    "engine-grpc-server",
    "engine-metrics-scraper",
    "engine-shared",
    "engine-storage",
    "engine-tests",
    "engine-wasm-prep",
]

exclude = [
    "contracts",
]
